version: 1

before:
  hooks:
    - go mod download

release:
  prerelease: "false"

env:
  - CGO_ENABLED=0

builds:
  - id: linux
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w -X "cmd.buildVersion={{.Version}}"
      - -s -w -X "cmd.buildCommit={{.Commit}}"
      - -s -w -X "cmd.buildOS={{.Os}}"
      - -s -w -X "cmd.buildArch={{.Arch}}"
      - -s -w -X "cmd.buildDate={{.Env.DATE}}"
      - -s -w -X "cmd.buildGoVersion={{.Env.GOVERSION}}"

  - id: osx
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "cmd.buildVersion={{.Version}}"
      - -s -w -X "cmd.buildCommit={{.Commit}}"
      - -s -w -X "cmd.buildOS={{.Os}}"
      - -s -w -X "cmd.buildArch={{.Arch}}"
      - -s -w -X "cmd.buildDate={{.Env.DATE}}"
      - -s -w -X "cmd.buildGoVersion={{.Env.GOVERSION}}"

  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "cmd.buildVersion={{.Version}}"
      - -s -w -X "cmd.buildCommit={{.Commit}}"
      - -s -w -X "cmd.buildOS={{.Os}}"
      - -s -w -X "cmd.buildArch={{.Arch}}"
      - -s -w -X "cmd.buildDate={{.Env.DATE}}"
      - -s -w -X "cmd.buildGoVersion={{.Env.GOVERSION}}"

archives:
  - format: tar.gz
    allow_different_binary_count: true
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: hibiscus
    repository:
      owner: jaehong21
      name: homebrew-tap
    commit_author:
      name: jaehong21
      email: dev@jaehong21.com
    directory: hibiscus
    homepage: https://jaehong21.com
    description: Modern terminal UI to interact with AWS resources
    test: |
      system "hibiscus version"
