version: 2

before:
  hooks:
    - go mod download

release:
  prerelease: "false"

# https://goreleaser.com/errors/multiple-binaries-archive/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - amd64
      - arm64
      # - arm
    goarm:
      - "7"
    ldflags:
      - -s -w -X "github.com/jaehong21/hibiscus/cmd.buildVersion={{.Version}}"
      - -s -w -X "github.com/jaehong21/hibiscus/cmd.buildCommit={{.Commit}}"
      - -s -w -X "github.com/jaehong21/hibiscus/cmd.buildOS={{.Os}}"
      - -s -w -X "github.com/jaehong21/hibiscus/cmd.buildArch={{.Arch}}"
      - -s -w -X "github.com/jaehong21/hibiscus/cmd.buildDate={{.Env.DATE}}"
      - -s -w -X "github.com/jaehong21/hibiscus/cmd.buildGoVersion={{.Env.GOVERSION}}"

archives:
  - formats: ["tar.gz"]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: |-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    # format_overrides:
    #   - goos: windows
    #     format: [ "zip" ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: hibiscus
    repository:
      owner: jaehong21
      name: homebrew-tap
    commit_author:
      name: jaehong21
      email: dev@jaehong21.com
    directory: .
    homepage: https://jaehong21.com
    description: Modern terminal UI to interact with AWS resources
    test: |
      system "hibiscus version"
