name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Set up Env
        id: setup-env
        run: |
          echo "DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "GOVERSION=$(go version | awk '{print $3}')" >> $GITHUB_OUTPUT

      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          # https://goreleaser.com/deprecations/#-rm-dist
          args: release --clean
        env:
          # https://goreleaser.com/errors/resource-not-accessible-by-integration/
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DATE: ${{ steps.setup-env.outputs.DATE }}
          GOVERSION: ${{ steps.setup-env.outputs.GOVERSION }}
